import os
import subprocess
import sys
from pathlib import Path

print(f"cwd: {os.getcwd()}")
print(f"exe: {sys.argv[1]}")

groups = [
  "ActivationOpNoInfTest",
  "ActivationOpTest",
  "AffineGridTest",
  "ArrayFeatureExtractorTest",
  "AttentionTest",
  "AttnLSTMTest",
  "BatchNormTest",
  "BeamSearchTest",
  "BiasGeluTest",
  "BiasSoftmaxTest",
  "BifurcationDetectorTest",
  "BitShiftOpTest",
  "CastMap",
  "CastOpTest",
  "CategoryMapper",
  "CDistOpTest",
  "Col2ImOpTest",
  "CompressTest",
  "ConcatOpTest",
  "ConstantOfShape",
  "ConstantOpTest",
  "ContribFunExpansionTest",
  "ContribOpAttentionTest",
  "ContribOpRotaryEmbeddingTest",
  "ContribOpTest",
  "ConvIntegerTest",
  "ConvTest",
  "ConvTransposeTest",
  "CPUExecutionProviderTest",
  "CropAndResizeTest",
  "CropContribOpTest",
  "CropOpTest",
  "CumSumTest",
  "DecoderAttentionTest",
  "DecoderMaskedMultiHeadAttentionTest",
  "DequantizeBFPTest",
  "DequantizeLinearContribOpTest",
  "DequantizeLinearOp21BlockedTest",
  "DequantizeLinearOpMLFloat16Test",
  "DequantizeLinearOpTest",
  "DequantizeLinearOpTest_BroadcastTensor",
  "DetOpTest",
  "Dropout",
  "DynamicQuantizeMatMul",
  "DynamicQuantLSTMTest",
  "DynamicSliceTest",
  "DynamicTimeWarping",
  "Einsum",
  "EinsumTransposeMatMulThreeInputsTests/EinsumTransposeMatMulThreeInputsTest",
  "EmbedLayerNormTest",
  "ExpandDimsTest",
  "ExpandOpTest",
  "EyeLikeOpTest",
  "FastGeluTest",
  "FeatureVectorizer",
  "FlattenOpModelTest",
  "FlattenOpTest",
  "FusedConvTest",
  "FusedMatMulOpTest",
  "GatedRelativePositionBiasTest",
  "GatherBlockQuantizedOpTest",
  "GatherElementsOpTest",
  "GatherNDOpTest",
  "GatherOpTest",
  "GemmaRotaryEmbeddingTest",
  "GemmOpTest",
  "GemmOptimizePackedVariants/GemmOptimizePackedTest",
  "GetExecutionProvidersTest",
  "GreedySearchTest",
  "GridsampleContribOpTest",
  "GroupNormTest",
  "GRUTest",
  "HardmaxOperator",
  "Identity",
  "If",
  "ImageScalerContribOpTest",
  "InstanceNormalizationOpTest",
  "InverseContribOpTest",
  "IsInfTest",
  "IsNaNOpTest",
  "LabelEncoder",
  "LayerNormTest",
  "LinearRegressorTest/LinearRegressorTest",
  "LogSoftmaxOperator",
  "LongformerAttentionTest",
  "Loop",
  "LpNormalizationTest",
  "LRNTest",
  "LSTMTest",
  "MathOpTest",
  "MatMul2Bits",
  "MatMulBnb4",
  "MatMulFpQ4",
  "MatmulInteger16OpTest",
  "MatmulIntegerOpTest",
  "MatMulIntegerToFloat",
  "MatMulNBits",
  "MatMulNBitsLutGemm",
  "MeanVarianceNormalizationTest",
  "MemcpyTest",
  "MLOpTest",
  "ModOpTest",
  "MoETest",
  "MultiHeadAttentionTest",
  "MurmurHash3OpTest",
  "MVNContribOpTest",
  "NGramRepeatBlockTest",
  "NhwcConvTest",
  "NhwcMaxPoolContribOpTest",
  "NonMaxSuppressionOpTest",
  "NonZeroOpTest",
  "Normalizer",
  "OneHotEncoderOpTest",
  "OneHotOpTest",
  "OpRegistrationTest",
  "OptionalOpTest",
  "PackedAttentionTest",
  "PackedMultiHeadAttentionTest",
  "PadOpTest",
  "PartitioningUtilsTest",
  "PoolTest",
  "QAttentionTest",
  "QEmbedLayerNormTest",
  "QLinearBinaryOpTest",
  "QLinearConcatS8",
  "QLinearConcatU8",
  "QLinearConvTest",
  "QLinearGlobalAveragePool",
  "QLinearLookupTableBasedOperatorTests",
  "QLinearPoolTest",
  "QLinearWhereTest",
  "QuantGemmTest",
  "QuantizeBFPTest",
  "QuantizeLinearContribOpTest",
  "QuantizeLinearMatmulOpTest",
  "QuantizeLinearOp21BlockedTest",
  "QuantizeLinearOpMLFloat16Test",
  "QuantizeLinearOpTest",
  "Random",
  "RangeTest",
  "ReductionOpTest",
  "RegexFullMatch",
  "RelativePositionBiasTest",
  "RemovePaddingTest",
  "ResizeOpTest",
  "RestorePaddingTest",
  "ReverseSequenceTest",
  "RMSNormalizationOpTest",
  "RNNTest",
  "RoiAlignTest",
  "RoIPoolTest",
  "RotaryEmbeddingTest",
  "RoundTest",
  "Scan8",
  "Scan9",
  "Scatter",
  "ScatterElements",
  "ScatterNDOpTest",
  "SequenceOpsTest",
  "ShapeInferenceTests",
  "ShapeOpTest",
  "SignalOpsTest",
  "SizeOpTest",
  "SkipGroupNormTest",
  "SkipLayerNormTest",
  "SliceTest",
  "SoftmaxOperator",
  "SparseToDenseMatMul",
  "SplitOperatorTest",
  "SqueezeOpTest",
  "StringConcat",
  "StringSplit",
  "TensorOpTest",
  "TfIdfVectorizerTest",
  "TopKOperator",
  "TransposeOpTest",
  "TriluContribOpTest",
  "TriluOpTest",
  "TriluTest",
  "UnfoldTensorOpTest",
  "Unique",
  "UniqueOpTest",
  "UnpoolTest",
  "UnsqueezeOpTest",
  "UpsampleOpTest",
  "WhereOpTest",
  "WriteScores",
]

for g in groups:
  print(f"Running {g} ...")
  args = [
    sys.argv[1],
    "--gtest_output=xml:" + g.replace('/', '_') + ".xml\"",
    '--gtest_filter=-"' + g + '*"'
  ]
  print("args: ", args)

  p = subprocess.Popen(
    args,
    text=True,
    universal_newlines=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    shell=False
  )

  with Path(g.replace('/', '_') + '.log').open('w') as strm:
    for line in p.stdout:
      strm.write(line)
    strm.flush()

  p.stdout.close()
  returncode = p.wait()

  print(f"Group {g} exited with exit code {returncode}.")

sys.exit(0)
