# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

'''
Script to run tests using onnxruntime_provider_test.
Includes a mapping of tests to explicitly exclude.

To run:
  python test_runner.py <path to onnxruntime_provider_test> <path to gtest results file>

'''

import os
import subprocess
import sys

print("cwd: ", os.getcwd())
print("exe: ", sys.argv[1])

# Map of test suite name to list of tests to exclude.
# Use "[*]" as value to exclude the entire test suite.
exclusions = {
  "ActivationOpNoInfTest": [],
  "ActivationOpTest": [
    "ActivationOpTest.Relu",
    "ActivationOpTest.Relu_fp16",
    "ActivationOpTest.Sigmoid_fp16",
    "ActivationOpTest.Tanh_fp16",
  ],
  "AffineGridTest": [],
  "ArrayFeatureExtractorTest": [],
  "AttentionTest": [],
  "AttnLSTMTest": [],
  "BatchNormTest": [
    "BatchNormTest.ForwardTrainingTestOpset14",
    "BatchNormTest.ForwardTrainingTestOpset15",
    "BatchNormTest.ForwardTrainingTestWithSavedOutputsOpset9",
  ],
  "BeamSearchTest": ["*"],
  "BiasGeluTest": ["BiasGeluTest.Float",],
  "BiasSoftmaxTest": [],
  "BifurcationDetectorTest": [],
  "BitShiftOpTest": [],
  "CastMap": [],
  "CastOpTest": [],
  "CategoryMapper": [],
  "CDistOpTest": [],
  "Col2ImOpTest": [],
  "CompressTest": [],
  "ConcatOpTest/0": [],
  "ConcatOpTest/1": [],
  "ConcatOpTest": [
    "ConcatOpTest.Concat1D_2",
    "ConcatOpTest.Concat2D_3",
    "ConcatOpTest.Concat2D_4",
  ],
  "ConstantOfShape": [
    "ConstantOfShape.DefaultValue",
    "ConstantOfShape.Float_Ones",
    "ConstantOfShape.Int32_Zeros",
    "ConstantOfShape.TypeTests",
  ],
  "ConstantOpTest": [
    "ConstantOpTest.GH11091",
  ],
  "ContribFunExpansionTest": [],
  "ContribOpAttentionTest": [],
  "ContribOpRotaryEmbeddingTest": [],
  "ContribOpTest": [],
  "ConvIntegerTest": [],
  "ConvTest": [],
  "ConvTransposeTest/0": [],
  "ConvTransposeTest/1": [],
  "ConvTransposeTest": [
    "ConvTransposeTest.ConvTranspose_1D_AsymmetricPads",
    "ConvTransposeTest.ConvTranspose_1D_AutoPad_SameLower",
    "ConvTransposeTest.ConvTranspose_1D_AutoPad_SameUpper",
    "ConvTransposeTest.ConvTranspose_1D_OutputShape_1_group_2_for_transpose_path",
    "ConvTransposeTest.ConvTranspose_2D_OutputShape_1",
    "ConvTransposeTest.ConvTranspose_2D_OutputShape_1_group_2_for_transpose_path",
    "ConvTransposeTest.ConvTranspose_AutoPad_with_non_default_strides",
    "ConvTransposeTest.ConvTranspose_InvalidBiasShape_1",
    "ConvTransposeTest.ConvTranspose_InvalidBiasShape_2",
    "ConvTransposeTest.ConvTranspose_InvalidKernelShape",
    "ConvTransposeTest.DimWithZero",
  ],
  "CPUExecutionProviderTest": [],
  "CropAndResizeTest": [
    "CropAndResizeTest.CropAndResize_1122",
    "CropAndResizeTest.CropAndResize_1133",
    "CropAndResizeTest.CropAndResize_1222",
    "CropAndResizeTest.CropAndResize_2122",
  ],
  "CropContribOpTest": [],
  "CropOpTest": [
    "CropOpTest.Crop_Border",
    "CropOpTest.Crop_Scale",
  ],
  "CumSumTest": [
    "CumSumTest._1DTest",
    "CumSumTest._1DTestdouble",
    "CumSumTest._1DTestdouble_WithInt64Axis",
    "CumSumTest._1DTestExclusive",
    "CumSumTest._1DTestExclusiveAxisHasSingleValue",
    "CumSumTest._1DTestFloat16",
    "CumSumTest._1DTestInt32",
    "CumSumTest._1DTestInt64",
    "CumSumTest._1DTestInvalidAxis",
    "CumSumTest._1DTestLong",
    "CumSumTest._1DTestNegAxis",
    "CumSumTest._1DTestReverse",
    "CumSumTest._1DTestReverseExclusive",
    "CumSumTest._2DTestAxis0",
    "CumSumTest._2DTestAxis1",
    "CumSumTest._2DTestExclusiveAxis0",
    "CumSumTest._2DTestExclusiveAxis1",
    "CumSumTest._3DTestAxis0",
    "CumSumTest._3DTestAxis0Exclusive",
    "CumSumTest._3DTestAxis0Reverse",
    "CumSumTest._3DTestAxis0ReverseExclusive",
    "CumSumTest._3DTestAxis1",
    "CumSumTest._3DTestAxis1Exclusive",
    "CumSumTest._3DTestAxis1Reverse",
    "CumSumTest._3DTestAxis1ReverseExclusive",
    "CumSumTest._3DTestAxis2",
    "CumSumTest._3DTestAxis2Exclusive",
    "CumSumTest._3DTestAxis2Reverse",
    "CumSumTest._3DTestAxis2ReverseExclusive",
  ],
  "DecoderAttentionTest": [],
  "DecoderMaskedMultiHeadAttentionTest": [],
  "DequantizeBFPTest": [],
  "DequantizeLinearContribOpTest": [
    "DequantizeLinearContribOpTest.DequantizeLinear_1",
    "DequantizeLinearContribOpTest.DequantizeLinear_2",
    "DequantizeLinearContribOpTest.DequantizeLinear_3",
  ],
  "DequantizeLinearOp21BlockedTest": [],
  "DequantizeLinearOpMLFloat16Test": [
    "DequantizeLinearOpMLFloat16Test.Float8",
    "DequantizeLinearOpMLFloat16Test.Scalar",
  ],
  "DequantizeLinearOpTest": [
    "DequantizeLinearOpTest.DequantizeLinear_per_tensor_float_int16_cpu",
    "DequantizeLinearOpTest.DequantizeLinear_per_tensor_float_int8",
    "DequantizeLinearOpTest.DequantizeLinear_per_tensor_float_uint16_cpu",
    "DequantizeLinearOpTest.DequantizeLinear_per_tensor_half_int8",
    "DequantizeLinearOpTest.Float8",
    "DequantizeLinearOpTest.Int16",
    "DequantizeLinearOpTest.Int2",
    "DequantizeLinearOpTest.Int2_LargeInitializerInput",
    "DequantizeLinearOpTest.Int2NoZeroPoint",
    "DequantizeLinearOpTest.Int4",
    "DequantizeLinearOpTest.Int4_LargeInitializerInput",
    "DequantizeLinearOpTest.Int4NoZeroPoint",
    "DequantizeLinearOpTest.Int8",
    "DequantizeLinearOpTest.Int8_Large",
    "DequantizeLinearOpTest.Int8_NonAlignedSize_Initializer",
    "DequantizeLinearOpTest.No_Zero_Point_int8",
    "DequantizeLinearOpTest.No_Zero_Point_uint8",
    "DequantizeLinearOpTest.Per_Channel_Axis_1_int32",
    "DequantizeLinearOpTest.Per_Channel_Axis_1_int8",
    "DequantizeLinearOpTest.Per_Channel_Axis_Default",
    "DequantizeLinearOpTest.Scalar",
    "DequantizeLinearOpTest.Uint16",
    "DequantizeLinearOpTest.UInt2",
    "DequantizeLinearOpTest.UInt2NoZeroPoint",
    "DequantizeLinearOpTest.UInt4",
    "DequantizeLinearOpTest.UInt4NoZeroPoint",
    "DequantizeLinearOpTest.Uint8",
    "DequantizeLinearOpTest.Uint8_Large",
    "DequantizeLinearOpTest.Without_Zero_Point",
    "DequantizeLinearOpTest.Zero_Point_int8",
    "DequantizeLinearOpTest.Zero_Point_uint8",
  ],
  "DequantizeLinearOpTest_BroadcastTensor": [],
  "DetOpTest": [],
  "Dropout": [
    "Dropout.WithOptionalOutputOpset10",
    "Dropout.WithOptionalOutputOpset7",
  ],
  "DynamicQuantizeMatMul": [],
  "DynamicQuantLSTMTest": [],
  "DynamicSliceTest": [],
  "DynamicTimeWarping": [],
  "Einsum": [],
  "EinsumTransposeMatMulThreeInputsTests/EinsumTransposeMatMulThreeInputsTest": [],
  "EmbedLayerNormTest": [],
  "ExpandDimsTest": [],
  "ExpandOpTest": [],
  "EyeLikeOpTest": [],
  "FastGeluTest": [],
  "FeatureVectorizer": [],
  "FlattenOpModelTest": [
    "FlattenOpModelTest.Flatten_broadcast",
  ],
  "FlattenOpTest": [
    "FlattenOpTest.Flatten_axis0",
    "FlattenOpTest.Flatten_axis2_bool",
    "FlattenOpTest.Flatten_axis3",
    "FlattenOpTest.Flatten_axis4",
    "FlattenOpTest.Flatten_neg_axis3",
  ],
  "FusedConvTest": [],
  "FusedMatMulOpTest": [
    "FusedMatMulOpTest.Float16_NoTranspose",
  ],
  "GatedRelativePositionBiasTest": [],
  "GatherBlockQuantizedOpTest": [],
  "GatherElementsOpTest": [
    "GatherElementsOpTest.IndicesOutOfBounds",
  ],
  "GatherNDOpTest": [],
  "GatherOpTest/0": [],
  "GatherOpTest/1": [],
  "GatherOpTest": [
    "GatherOpTest.Gather_axis1_indices2d_int32",
    "GatherOpTest.Gather_axis1_indices2d_int8",
    "GatherOpTest.Gather_axis1_neg_indices2d_int8",
  ],
  "GemmaRotaryEmbeddingTest": [],
  "GemmOpTest": [
    "GemmOpTest.Gemm2DBroadcast_1_bfloat16",
    "GemmOpTest.Gemm2DBroadcast_2_bfloat16",
    "GemmOpTest.GemmNaN_bfloat16",
    "GemmOpTest.GemmNoTrans_f16",
    "GemmOpTest.GemmScalarBroadcast_bfloat16",
    "GemmOpTest.GemmTransB_f16",
  ],
  "GemmOpTypedTests/0": [
    "GemmOpTypedTests/0.GemmEmptyTensor",
    "GemmOpTypedTests/0.MissingBias",
    "GemmOpTypedTests/0.TestGemmWithAlphaOpset11",
  ],
  "GemmOpTypedTests/1": [
    "GemmOpTypedTests/1.TestGemmAlpha",
    "GemmOpTypedTests/1.TestGemmAlphaBeta",
    "GemmOpTypedTests/1.TestGemmBeta",
    "GemmOpTypedTests/1.TestGemmNaN",
    "GemmOpTypedTests/1.TestGemmZeroAlpha",
    "GemmOpTypedTests/1.TestGemmZeroAlphaBeta",
    "GemmOpTypedTests/1.TestGemmZeroBeta",
  ],
  "GemmOptimizePackedVariants/GemmOptimizePackedTest": [],
  "GetExecutionProvidersTest": [],
  "GreedySearchTest": [],
  "GridsampleContribOpTest": [],
  "GroupNormTest": [],
  "GRUTest": [],
  "HardmaxOperator": [],
  "GridSampleTest/0": [],
  "GridSampleTest/1": [],
  "Identity": [
    "Identity.OptionalTensorSequenceType_None",
    "Identity.OptionalTensorSequenceType_NonNone",
    "Identity.OptionalTensorType_None",
    "Identity.OptionalTensorType_NonNone",
    "Identity.StringType",
  ],
  "If": [
    "If.TestIfWithOptionalTypeTensorAsOutput",
    "If.NoShapeInMainGraph_ShapeInSubgraph_True",
    "If.NoShapeInMainGraph_ShapeInSubgraph_False",
    "If.SymbolicShapeInMainGraph_NoShapeInSubgraph_True",
    "If.SymbolicShapeInMainGraph_NoShapeInSubgraph_False",
    "If.Opset11ThenAndElseBranchesProduceDifferentOutputShapes",
  ],
  "ImageScalerContribOpTest": [
    "ImageScalerContribOpTest.ImageScalerTest",
  ],
  "InstanceNormalizationOpTest/0": [],
  "InstanceNormalizationOpTest/1": [],
  "InstanceNormalizationOpTest": [
    "InstanceNormalizationOpTest.InstanceNorm",
    "InstanceNormalizationOpTest.InstanceNorm_2",
    "InstanceNormalizationOpTest.InstanceNormBatch1",
    "InstanceNormalizationOpTest.InstanceNormBatch1_fp16",
    "InstanceNormalizationOpTest.InstanceNormBatch2",
    "InstanceNormalizationOpTest.InstanceNormBatch2_fp16",
    "InstanceNormalizationOpTest.InstanceNormNCHW",
  ],
  "InverseContribOpTest": [],
  "IsInfTest": [
    "IsInfTest.test_isinf_bfloat16",
    "IsInfTest.test_Float8E4M3FN",
  ],
  "IsNaNOpTest": [
    "IsNaNOpTest.IsNaNBFloat16_20",
    "IsNaNOpTest.IsNaNFloat8E4M3FN",
  ],
  "LabelEncoder": [
    "LabelEncoder.Int64toStringOpset4",
    "LabelEncoder.StringToFloatOpset4",
    "LabelEncoder.StringToDoubleOpset4",
    "LabelEncoder.NaNsMappedTogetherOpset4",
    "LabelEncoder.DoubleNaNsMappedTogetherOpset4",
  ],
  "LayerNormTest/0": ["*"],
  "LayerNormTest/1": ["*"],
  "LayerNormTest": [
    "LayerNormTest.BERTLayerNorm",
    "LayerNormTest.BERTLayerNorm_NoBias",
    "LayerNormTest.LayerNorm_BFloat16Input",
    "LayerNormTest.LayerNorm_Scale_Bias_Float16Input",
    "LayerNormTest.LayerNorm_Scale_Bias_Float16InputScaleBiasOutput",
    "LayerNormTest.LayerNorm_Scale_Bias_Float16InputScaleBiasOutput_Initializers",
    "LayerNormTest.LayerNorm_Scale_Bias_Float16ScaleBiasOutput",
    "LayerNormTest.LayerNorm_Scale_Float16Input",
    "LayerNormTest.LayerNorm_Scale_Float16InputScaleOutput",
    "LayerNormTest.LayerNorm_Scale_Float16InputScaleOutput_Initializers",
    "LayerNormTest.LayerNorm_Scale_Float16ScaleOutput",
  ],
  "LinearRegressorTest/LinearRegressorTest": [],
  "LogSoftmaxOperator": [],
  "LongformerAttentionTest": [],
  "Loop": [
    "Loop.ExitDueToCond_DimsInMainGraph",
    "Loop.ExitDueToCond_DimsInMainGraph_ScalarIter",
    "Loop.ExitDueToCond_DimsInMainGraph_ScalarCond",
    "Loop.ExitDueToCond_DimsInMainGraph_ScalarBoth",
    "Loop.ExitDueToCond_DimsInSubGraph",
    "Loop.ExitDueToCond_DimsInSubGraph_ScalarIter",
    "Loop.ExitDueToCond_DimsInSubGraph_ScalarCond",
    "Loop.ExitDueToCond_DimsInSubGraph_ScalarBoth",
    "Loop.LoopSubgraphRankMismatch",
    "Loop.ExitDueToMaxIterations",
    "Loop.ZeroIterations",
    "Loop.SubgraphTypeOverride",
    "Loop.SubgraphInputShadowsOuterScopeValue",
    "Loop.BugFixIssue4031_implicit_input_handling",
    "Loop.IterationCountAsOutput",
  ],
  "LpNormalizationTest": [],
  "LRNTest": [],
  "LSTMTest": [],
  "MathOpTest": [
    "MathOpTest.Abs_int32",
    "MathOpTest.Abs_int8",
    "MathOpTest.Add_Broadcast_2x1x1_3x4",
    "MathOpTest.Add_Broadcast_2x1x4_1x3x1",
    "MathOpTest.Add_Broadcast_2x2x2_1x2x2",
    "MathOpTest.Add_Broadcast_MultidirectionalAB",
    "MathOpTest.Add_Broadcast_MultidirectionalBA",
    "MathOpTest.Add_int32",
    "MathOpTest.Clip",
    "MathOpTest.Clip_Default_int64",
    "MathOpTest.Clip_Default_int8",
    "MathOpTest.Clip_Default_uint64",
    "MathOpTest.Clip_Default_uint8",
    "MathOpTest.Clip_int32",
    "MathOpTest.Clip_Relu",
    "MathOpTest.Clip_Relu1",
    "MathOpTest.Clip_Relu6",
    "MathOpTest.Clip_uint32",
    "MathOpTest.ClipDimWithZero",
    "MathOpTest.CosDouble",
    "MathOpTest.DimWithZeroHandling",
    "MathOpTest.Div_int32",
    "MathOpTest.Div_int64",
    "MathOpTest.Equal_int16",
    "MathOpTest.Equal_int8",
    "MathOpTest.Equal_uint16",
    "MathOpTest.Equal_uint32",
    "MathOpTest.Equal_uint64",
    "MathOpTest.Equal_uint8",
    "MathOpTest.Exp_double",
    "MathOpTest.Exp_float",
    "MathOpTest.Greater_9_int16",
    "MathOpTest.Greater_9_int8",
    "MathOpTest.Greater_9_uint16",
    "MathOpTest.Greater_9_uint32",
    "MathOpTest.Greater_9_uint64",
    "MathOpTest.Greater_9_uint8",
    "MathOpTest.GreaterOrEqual_12_double",
    "MathOpTest.GreaterOrEqual_12_float",
    "MathOpTest.GreaterOrEqual_12_int16",
    "MathOpTest.GreaterOrEqual_12_int32",
    "MathOpTest.GreaterOrEqual_12_int64",
    "MathOpTest.GreaterOrEqual_12_int8",
    "MathOpTest.GreaterOrEqual_12_uint16",
    "MathOpTest.GreaterOrEqual_12_uint32",
    "MathOpTest.GreaterOrEqual_12_uint64",
    "MathOpTest.GreaterOrEqual_12_uint8",
    "MathOpTest.GreaterOrEqual_16_bfloat16",
    "MathOpTest.GreaterOrEqual_broadcastAB",
    "MathOpTest.GreaterOrEqual_broadcastBA",
    "MathOpTest.GreaterOrEqual_multidirectional_broadcastAB",
    "MathOpTest.GreaterOrEqual_multidirectional_broadcastBA",
    "MathOpTest.Less_int16_Scalar1",
    "MathOpTest.Less_int8_Scalar1",
    "MathOpTest.Less_uint16_Scalar1",
    "MathOpTest.Less_uint32_Scalar1",
    "MathOpTest.Less_uint64_Scalar1",
    "MathOpTest.Less_uint8_Scalar1",
    "MathOpTest.LessOrEqual",
    "MathOpTest.LessOrEqual_bfloat16",
    "MathOpTest.LessOrEqual_bfloat16_broadcastAB",
    "MathOpTest.LessOrEqual_bfloat16_broadcastBA",
    "MathOpTest.LessOrEqual_bfloat16_Scalar0",
    "MathOpTest.LessOrEqual_bfloat16_Scalar1",
    "MathOpTest.LessOrEqual_broadcastAB",
    "MathOpTest.LessOrEqual_broadcastBA",
    "MathOpTest.LessOrEqual_int16_Scalar1",
    "MathOpTest.LessOrEqual_int64_Scalar1",
    "MathOpTest.LessOrEqual_int8_Scalar1",
    "MathOpTest.LessOrEqual_multidirectional_bfloat16_broadcastAB",
    "MathOpTest.LessOrEqual_multidirectional_bfloat16_broadcastBA",
    "MathOpTest.LessOrEqual_multidirectional_broadcastAB",
    "MathOpTest.LessOrEqual_multidirectional_broadcastBA",
    "MathOpTest.LessOrEqual_Scalar0",
    "MathOpTest.LessOrEqual_Scalar1",
    "MathOpTest.LessOrEqual_uint16_Scalar1",
    "MathOpTest.LessOrEqual_uint32_Scalar1",
    "MathOpTest.LessOrEqual_uint64_Scalar1",
    "MathOpTest.LessOrEqual_uint8_Scalar1",
    "MathOpTest.MatMul_Float16",
    "MathOpTest.Max_12_Double",
    "MathOpTest.Max_12_Float",
    "MathOpTest.Max_12_Int32",
    "MathOpTest.Max_12_Int64",
    "MathOpTest.Max_12_Int8",
    "MathOpTest.Max_12_MLFloat16",
    "MathOpTest.Max_12_MLFloat16_Scalar0",
    "MathOpTest.Max_12_MLFloat16_Scalar1",
    "MathOpTest.Max_12_MLFloat16_Scalar2",
    "MathOpTest.Max_12_UInt32",
    "MathOpTest.Max_12_UInt64",
    "MathOpTest.Max_12_UInt8",
    "MathOpTest.Max_6",
    "MathOpTest.Max_8_2inputbroadcast",
    "MathOpTest.Max_8_Double",
    "MathOpTest.Max_8_Float",
    "MathOpTest.Mean_6",
    "MathOpTest.Mean_8",
    "MathOpTest.Min_12_Double",
    "MathOpTest.Min_12_Float",
    "MathOpTest.Min_12_Float_2_Input",
    "MathOpTest.Min_12_Int32",
    "MathOpTest.Min_12_Int64",
    "MathOpTest.Min_12_Int8",
    "MathOpTest.Min_12_MLFloat16",
    "MathOpTest.Min_12_MLFloat16_Scalar0",
    "MathOpTest.Min_12_MLFloat16_Scalar1",
    "MathOpTest.Min_12_UInt32",
    "MathOpTest.Min_12_UInt64",
    "MathOpTest.Min_12_UInt8",
    "MathOpTest.Min_6",
    "MathOpTest.Mul_int32",
    "MathOpTest.Neg_int16",
    "MathOpTest.Neg_int32",
    "MathOpTest.Neg_int64",
    "MathOpTest.Neg_int8",
    "MathOpTest.ShrinkInt8Type",
    "MathOpTest.ShrinkMLFloat16Type",
    "MathOpTest.Sub_int32",
    "MathOpTest.Sum_6",
    "MathOpTest.Sum_6_double",
    "MathOpTest.Sum_8_Test1",
    "MathOpTest.Sum_8_Test1_double",
    "MathOpTest.Sum_8_Test2",
    "MathOpTest.Sum_8_Test2_double",
  ],
  "MatMul2Bits": [],
  "MatMulBnb4": [],
  "MatMulFpQ4": [],
  "MatmulInteger16OpTest": [],
  "MatmulIntegerOpTest": [],
  "MatMulIntegerToFloat": [],
  "MatMulNBits": [],
  "MatMulNBitsLutGemm": [],
  "MeanVarianceNormalizationTest": [],
  "MemcpyTest": [],
  "MLOpTest": [],
  "ModOpTest": [
    "ModOpTest.Int8_mixed_sign",
    "ModOpTest.Int8_mixed_sign_fmod",
  ],
  "MoETest": [],
  "MultiHeadAttentionTest": [
    "MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize40",
    "MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_RightSidePadding_Mask1D",
    "MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_RightSidePadding_Mask2D",
    "MultiHeadAttentionTest.CrossAttention_Batch1_HeadSize32_LeftSidePadding_Mask2D",
    "MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_NoBias_NoMask_PackedKV",
    "MultiHeadAttentionTest.SelfAttention_Batch2_HeadSize32_NoBias_NoMask_PackedQKV",
    "MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize16_8",
    "MultiHeadAttentionTest.CrossAttention_Batch1_HeadSize16",
    "MultiHeadAttentionTest.CrossAttention_Batch1_HeadSize8",
    "MultiHeadAttentionTest.CrossAttentionWithPast",
    "MultiHeadAttentionTest.SelfAttention_WithPast_WithAttnBias_ForT5",
    "MultiHeadAttentionTest.AttentionCutlassRelPosBias",
    "MultiHeadAttentionTest.CrossAttention_DiffSequenceLengths",
    "MultiHeadAttentionTest.SelfAttention_WithPastAndPresent_NoMask_NoRelPosBias",
    "MultiHeadAttentionTest.SelfAttention_PastPresentBufferShare_UsingDMMHAInsideMHA",
    "MultiHeadAttentionTest.CrossAttention_DiffSequenceLengths_UsingDMMHAInsideMHA",
  ],
  "MurmurHash3OpTest": [],
  "MVNContribOpTest": [],
  "NGramRepeatBlockTest": [],
  "NhwcConvTest": [],
  "NhwcMaxPoolContribOpTest": [],
  "NonMaxSuppressionOpTest": [
    "NonMaxSuppressionOpTest.InvalidIOUThreshold",
    "NonMaxSuppressionOpTest.WithIOUThreshold",
    "NonMaxSuppressionOpTest.CenterPointBoxFormat",
    "NonMaxSuppressionOpTest.TwoClasses",
    "NonMaxSuppressionOpTest.TwoBatches_OneClass",
    "NonMaxSuppressionOpTest.TwoBatches_TwoClasses",
    "NonMaxSuppressionOpTest.WithScoreThreshold",
    "NonMaxSuppressionOpTest.WithoutScoreThreshold",
    "NonMaxSuppressionOpTest.WithScoreThresholdZeroScores",
    "NonMaxSuppressionOpTest.FlippedCoordinates",
    "NonMaxSuppressionOpTest.SelectTwo",
    "NonMaxSuppressionOpTest.SelectThirty",
    "NonMaxSuppressionOpTest.InconsistentBoxAndScoreShapes",
    "NonMaxSuppressionOpTest.BigIntMaxOutputBoxesPerClass",
    "NonMaxSuppressionOpTest.WithIOUThresholdOpset11",
  ],
  "NonZeroOpTest": [
    "NonZeroOpTest.BasicNumeric",
    "NonZeroOpTest.BasicBool",
    "NonZeroOpTest.ThreeDims",
    "NonZeroOpTest.Scalar",
  ],
  "Normalizer": [],
  "OneHotEncoderOpTest": [],
  "OneHotOpTest": [],
  "OpRegistrationTest": [],
  "OptionalOpTest": [
    "OptionalOpTest.OptionalOpsValidateOrtValueReUseForOptionalTensors",
    "OptionalOpTest.OptionalOpsValidateOrtValueReUseForOptionalTensorSequence",
    "OptionalOpTest.OptionalSeqTensorCreateFromSeqTensor",
    "OptionalOpTest.OptionalSeqTensorCreateFromTypeProto",
    "OptionalOpTest.OptionalSeqTensorGetElement",
    "OptionalOpTest.OptionalSeqTensorHasElement_False",
    "OptionalOpTest.OptionalSeqTensorHasElement_True",
    "OptionalOpTest.OptionalTensorCreateFromTensor",
    "OptionalOpTest.OptionalTensorCreateFromTypeProto",
    "OptionalOpTest.OptionalTensorGetElement",
    "OptionalOpTest.OptionalTensorHasElement_False",
    "OptionalOpTest.OptionalTensorHasElement_True",
  ],
  "PackedAttentionTest": [],
  "PackedMultiHeadAttentionTest": [
    "PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_cutlass",
    "PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_trt",
    "PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_unfused",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_AttnBias",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_BroadcastAttnBias_cutlass",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_BroadcastAttnBias_unfused",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_cutlass",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_trt",
    "PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_unfused",
    "PackedMultiHeadAttentionTest.Q_K_V_NoPadding_Bias_AttnBias_cutlass",
    "PackedMultiHeadAttentionTest.Q_K_V_NoPadding_Bias_AttnBias_unfused",
    "PackedMultiHeadAttentionTest.Q_K_V_NoPadding_NoBias_trt",
  ],
  "PadOpTest/0": [
    "PadOpTest/0.Pad_Edge_DimWithZeroInput",
    "PadOpTest/0.Pad_Reflect_DimWithZeroInput",
  ],
  "PadOpTest/1": [
    "PadOpTest/1.Pad_Edge_DimWithZeroInput",
    "PadOpTest/1.Pad_Reflect_DimWithZeroInput",
  ],
  "PadOpTest/2": [
    "PadOpTest/2.Pad_3D_complex",
    "PadOpTest/2.Pad_Constant_1D",
    "PadOpTest/2.Pad_Constant_1D_Zero",
    "PadOpTest/2.Pad_Constant_2D",
    "PadOpTest/2.Pad_Constant_2D_negative_pads_1",
    "PadOpTest/2.Pad_Constant_2D_negative_pads_2",
    "PadOpTest/2.Pad_Constant_3D_Inner_No_Padding",
    "PadOpTest/2.Pad_Constant_3D_negative_pads",
    "PadOpTest/2.Pad_Constant_4D_negative_pads",
    "PadOpTest/2.Pad_Constant_DimWithZeroInput",
    "PadOpTest/2.Pad_Edge_1D",
    "PadOpTest/2.Pad_Edge_2D",
    "PadOpTest/2.Pad_Edge_3D",
    "PadOpTest/2.Pad_Edge_3D_Inner_No_Padding",
    "PadOpTest/2.Pad_Edge_3D_Last_Pad_Slice_Inner_No_Padding",
    "PadOpTest/2.Pad_Edge_3D_Last_Slice_Inner_No_Padding",
    "PadOpTest/2.Pad_Edge_DimWithZeroInput",
    "PadOpTest/2.Pad_Reflect_1D",
    "PadOpTest/2.Pad_Reflect_2D",
    "PadOpTest/2.Pad_Reflect_3D_Inner_No_Padding",
    "PadOpTest/2.Pad_Reflect_3D_Last_Pad_Slice_Inner_No_Padding",
    "PadOpTest/2.Pad_Reflect_3D_Last_Slice_Inner_No_Padding",
    "PadOpTest/2.Pad_Reflect_DimWithZeroInput",
    "PadOpTest/2.Pad_Spec_Example",
    "PadOpTest/2.Pad_Wrap_1D",
    "PadOpTest/2.Pad_Wrap_2D",
    "PadOpTest/2.Pad_wrap_3D_Inner_No_Padding",
    "PadOpTest/2.Pad_wrap_3D_Inner_No_Padding2",
  ],
  "PadOpTest/3": [
    "PadOpTest/3.Pad_Edge_DimWithZeroInput",
    "PadOpTest/3.Pad_Reflect_DimWithZeroInput",
  ],
  "PadOpTest/4": [
    "PadOpTest/4.Pad_Edge_DimWithZeroInput",
    "PadOpTest/4.Pad_Reflect_DimWithZeroInput",
  ],
  "PadOpTest/5": [],
  "PadOpTest/6": [],
  "PadOpTest/7": [],
  "PadOpTest": [
    "PadOpTest.BoolType",
    "PadOpTest.ConstantPadAxes",
    "PadOpTest.ConstantPadAxesOutOfOrder",
    "PadOpTest.ConstantPadAxesTest1",
    "PadOpTest.ConstantPadAxesTest2",
    "PadOpTest.ConstantPadAxesTest3",
    "PadOpTest.ConstantPadAxesTest4",
    "PadOpTest.ConstantPadAxesWithOneDimensionSpecified",
    "PadOpTest.ConstantPadLargeNegativePadNoOutput",
    "PadOpTest.ConstantPadNegativeAxes",
    "PadOpTest.EdgeMode_ZeroExtentFails",
    "PadOpTest.Pad_Edge_DimWithZeroInput",
    "PadOpTest.Pad_Reflect_BothPadsExceedExtent_1D",
    "PadOpTest.Pad_Reflect_DimWithZeroInput",
    "PadOpTest.Pad_Reflect_NegativeFront_PositiveBack",
    "PadOpTest.Pad_Reflect_PadEqualsExtent_Fails",
    "PadOpTest.Pad_Reflect_PadEqualsExtentMinus1_Succeeds",
    "PadOpTest.Pad_Reflect_PostPadExceedsExtent_1D",
    "PadOpTest.Pad_Reflect_PostPadExceedsExtent_2D",
    "PadOpTest.Pad_Reflect_PrePadExceedsExtent_1D",
    "PadOpTest.Pad_Reflect_PrePadExceedsExtent_2D",
    "PadOpTest.Pad_Reflect_SlicedExtentExceeded",
    "PadOpTest.Pad_Wrap_NegativeFront_PositiveBack",
  ],
  "PartitioningUtilsTest": [],
  "PoolTest/0": [],
  "PoolTest/1": [],
  "PoolTest": [
    "PoolTest.AveragePool_10_ceil1_2d",
    "PoolTest.AveragePool_19_ceil_count_include_pad_1d",
    "PoolTest.AveragePool_19_dilation_2d",
    "PoolTest.AveragePool_CountIncludePad_AsymmetricPads",
    "PoolTest.AveragePool_DefaultStrides",
    "PoolTest.AveragePool_IncludePadPixel",
    "PoolTest.AveragePool3D_CountIncludePad_AsymmetricPads",
    "PoolTest.LpPool1d",
    "PoolTest.LpPoolCeilMode",
    "PoolTest.MaxPool",
    "PoolTest.MaxPool_10_Dilation_1d",
    "PoolTest.MaxPool_10_Dilation_2d",
    "PoolTest.MaxPool_10_Dilation_2d_int8",
    "PoolTest.MaxPool_10_Dilation_Ceil0_2d",
    "PoolTest.MaxPool_10_Dilation_Ceil1_2d",
    "PoolTest.MaxPool_10_DilationPadding_1d",
    "PoolTest.MaxPool_10_DilationPadding_2d",
    "PoolTest.MaxPool_10_DilationPadding_3d",
    "PoolTest.MaxPool_12_Dilation_Ceil0_2d_int8",
    "PoolTest.MaxPool_DefaultDilations",
    "PoolTest.MaxPool_DefaultDilations_int8",
    "PoolTest.MaxPool_DefaultDilations_uint8",
    "PoolTest.MaxPool_DilationPadding_3d",
    "PoolTest.MaxPool_F16",
    "PoolTest.MaxPool1D_8_With_Index",
    "PoolTest.MaxPool1D_case1",
    "PoolTest.MaxPool1D_case2",
    "PoolTest.MaxPool1D_case3",
    "PoolTest.MaxPoolDimWithZeroForN",
  ],
  "QAttentionTest": [
    "QAttentionTest.QAttentionPastState_u8s8",
    "QAttentionTest.QAttentionPastState_u8u8",
  ],
  "QEmbedLayerNormTest": [],
  "QLinearBinaryOpTest": [],
  "QLinearConcatS8": [],
  "QLinearConcatU8": [],
  "QLinearConvTest": [],
  "QLinearGlobalAveragePool": [],
  "QLinearLookupTableBasedOperatorTests": [],
  "QLinearPoolTest": [],
  "QLinearWhereTest": [],
  "QuantGemmTest": [],
  "QuantizeBFPTest": [],
  "QuantizeLinearContribOpTest": [
    "QuantizeLinearContribOpTest.QuantizeLinear_per_channel",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_channel_negative_axis",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_tensor_float_int16",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_tensor_float_int8",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_tensor_float_uint16",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_tensor_half_int8",
    "QuantizeLinearContribOpTest.QuantizeLinear_per_tensor_half_uint8",
  ],
  "QuantizeLinearMatmulOpTest": [
    "QuantizeLinearMatmulOpTest.QLinearMatMulPrePack",
  ],
  "QuantizeLinearOp21BlockedTest": [],
  "QuantizeLinearOpMLFloat16Test": [
    "QuantizeLinearOpMLFloat16Test.Uint8",
  ],
  "QuantizeLinearOpTest": [
    "QuantizeLinearOpTest.2D",
    "QuantizeLinearOpTest.Float8",
    "QuantizeLinearOpTest.Int16",
    "QuantizeLinearOpTest.Int2",
    "QuantizeLinearOpTest.Int4",
    "QuantizeLinearOpTest.Int8",
    "QuantizeLinearOpTest.Int8_NegativeZeroPoint",
    "QuantizeLinearOpTest.Int8_PositiveZeroPoint",
    "QuantizeLinearOpTest.Large_Int2",
    "QuantizeLinearOpTest.Large_UInt2",
    "QuantizeLinearOpTest.OddLarge_Int2",
    "QuantizeLinearOpTest.OddLarge_Int4",
    "QuantizeLinearOpTest.OddLarge_UInt2",
    "QuantizeLinearOpTest.OddLarge_UInt4",
    "QuantizeLinearOpTest.Per_Channel_Axis_0",
    "QuantizeLinearOpTest.Per_Channel_Axis_Default",
    "QuantizeLinearOpTest.Per_Channel_Axis_neg",
    "QuantizeLinearOpTest.QuantizeLinear_With_Zero_Dim1",
    "QuantizeLinearOpTest.QuantizeLinear_With_Zero_Point0",
    "QuantizeLinearOpTest.QuantizeLinear_Without_Zero_Point_Opset10",
    "QuantizeLinearOpTest.QuantizeLinear_Without_Zero_Point_Opset13",
    "QuantizeLinearOpTest.Scalar",
    "QuantizeLinearOpTest.Uint16",
    "QuantizeLinearOpTest.UInt2",
    "QuantizeLinearOpTest.UInt4",
    "QuantizeLinearOpTest.Uint8",
  ],
  "Random": [
    "Random.RandomNormalLike3DDouble",
    "Random.RandomNormalLikeInferDType",
    "Random.RandomUniform1DFloat",
    "Random.RandomUniformLikeInferDType",
  ],
  "RangeTest": [],
  "ReductionOpTest/0": [],
  "ReductionOpTest/1": [],
  "ReductionOpTest": [
    "ReductionOpTest.ArgMax_do_not_keepdims",
    "ReductionOpTest.ArgMax_do_not_keepdims_2",
    "ReductionOpTest.ArgMax_Double_Type",
    "ReductionOpTest.ArgMax_float_first_index_random",
    "ReductionOpTest.ArgMax_int32_last_index_dups",
    "ReductionOpTest.ArgMax_int32_last_index_nodups",
    "ReductionOpTest.ArgMax_int8",
    "ReductionOpTest.ArgMax2D",
    "ReductionOpTest.ArgMax2D_dim1",
    "ReductionOpTest.ArgMax2D_select_last",
    "ReductionOpTest.ArgMin_do_not_keepdims_2",
    "ReductionOpTest.ArgMin_do_not_keepdims_2_select_last",
    "ReductionOpTest.ArgMin_Double_Precision",
    "ReductionOpTest.ArgMin_Double_Type",
    "ReductionOpTest.ArgMin_float_first_index_random",
    "ReductionOpTest.ArgMin_int32_select_last",
    "ReductionOpTest.ArgMin_int8",
    "ReductionOpTest.ReduceDimWithZero1",
    "ReductionOpTest.ReduceDimWithZero2",
    "ReductionOpTest.ReduceL1_do_not_keep_dims",
    "ReductionOpTest.ReduceL1_do_not_keep_dims_2",
    "ReductionOpTest.ReduceL1_do_not_keep_dims_2_bfloat16",
    "ReductionOpTest.ReduceL1_do_not_keep_dims_bfloat16",
    "ReductionOpTest.ReduceL1_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceL10DTensor",
    "ReductionOpTest.ReduceL2_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceL2_do_not_keepdims",
    "ReductionOpTest.ReduceL2_do_not_keepdims_2",
    "ReductionOpTest.ReduceL2_int32",
    "ReductionOpTest.ReduceL2_int64",
    "ReductionOpTest.ReduceL2_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceL20DTensor",
    "ReductionOpTest.ReduceLogSum_do_not_keepdims_2",
    "ReductionOpTest.ReduceLogSum0DTensor",
    "ReductionOpTest.ReduceLogSumExp_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceLogSumExp_default_axes_do_not_keep_dims_double",
    "ReductionOpTest.ReduceLogSumExp_do_not_keepdims",
    "ReductionOpTest.ReduceLogSumExp_do_not_keepdims_2",
    "ReductionOpTest.ReduceLogSumExp_do_not_keepdims_2_double",
    "ReductionOpTest.ReduceLogSumExp_do_not_keepdims_double",
    "ReductionOpTest.ReduceLogSumExp0DTensor",
    "ReductionOpTest.ReduceLogSumExp0DTensor_double",
    "ReductionOpTest.ReduceLogSumExp1DTensor",
    "ReductionOpTest.ReduceMax_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceMax_do_not_keepdims_2",
    "ReductionOpTest.ReduceMax_int32",
    "ReductionOpTest.ReduceMax_int64",
    "ReductionOpTest.ReduceMax_int8",
    "ReductionOpTest.ReduceMax_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceMax_uint8",
    "ReductionOpTest.ReduceMax0DTensor",
    "ReductionOpTest.ReduceMaxAxesInitializerOpset18",
    "ReductionOpTest.ReduceMean_axes_input",
    "ReductionOpTest.ReduceMean_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceMean_default_axes_do_not_keep_dims_double",
    "ReductionOpTest.ReduceMean_do_not_keepdims_2",
    "ReductionOpTest.ReduceMean_do_not_keepdims_2_double",
    "ReductionOpTest.ReduceMean_do_not_keepdims_axes_input_initializer",
    "ReductionOpTest.ReduceMean_keepdims_results_in_noop",
    "ReductionOpTest.ReduceMean_keepdims_results_in_shape_change",
    "ReductionOpTest.ReduceMean_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceMean0DTensor",
    "ReductionOpTest.ReduceMean0DTensor_double",
    "ReductionOpTest.ReduceMeanAxesInitializerOpset18",
    "ReductionOpTest.ReduceMin_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceMin_default_axes_do_not_keep_dims_2D",
    "ReductionOpTest.ReduceMin_do_not_keepdims_2",
    "ReductionOpTest.ReduceMin_int8",
    "ReductionOpTest.ReduceMin_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceMin_uint8",
    "ReductionOpTest.ReduceMin0DTensor",
    "ReductionOpTest.ReduceMinAxesInitializerOpset18",
    "ReductionOpTest.ReduceProd_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceProd_do_not_keepdims_2",
    "ReductionOpTest.ReduceProd_noop_axes_input_initializer_opset_18",
    "ReductionOpTest.ReduceProd0DTensor",
    "ReductionOpTest.ReduceProdAxesInitializerOpset18",
    "ReductionOpTest.ReduceSum_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceSum_do_not_keepdims_2",
    "ReductionOpTest.ReduceSum_do_not_keepdims_axes_input_initializer",
    "ReductionOpTest.ReduceSum_do_not_keepdims_axes_input_not_initializer",
    "ReductionOpTest.ReduceSum_empty_axes_input_initializer_opset_13",
    "ReductionOpTest.ReduceSum_int32_axes_input",
    "ReductionOpTest.ReduceSum_noop_axes_input_initializer_opset_13",
    "ReductionOpTest.ReduceSum_ReduceDimWithZero3",
    "ReductionOpTest.ReduceSum_RKRK_keepdims",
    "ReductionOpTest.ReduceSum0DTensor",
    "ReductionOpTest.ReduceSumAxesInitializerOpset13",
    "ReductionOpTest.ReduceSumSquare_default_axes_do_not_keep_dims",
    "ReductionOpTest.ReduceSumSquare_do_not_keepdims_2",
    "ReductionOpTest.ReduceSumSquare_int32",
    "ReductionOpTest.ReduceSumSquare_int64",
    "ReductionOpTest.ReduceSumSquare0DTensor",
  ],
  "RegexFullMatch": [],
  "RelativePositionBiasTest": [],
  "RemovePaddingTest": [],
  "ResizeOpTest/0": [],
  "ResizeOpTest/1": [],
  "ResizeOpTest": [
    "ResizeOpTest.Antialias_Large_half_pixel",
    "ResizeOpTest.Axes_and_Scale_18",
    "ResizeOpTest.NhwcResizeOpLinearDownSampleTest_4DBilinear_align_corners_int8",
    "ResizeOpTest.NhwcResizeOpLinearDownSampleTest_4DBilinear_pytorch_half_pixel_int8",
    "ResizeOpTest.NhwcResizeOpLinearDownSampleTest_tf_crop_and_resize_with_extrapolation",
    "ResizeOpTest.NhwcResizeOpLinearUpSampleTest_4DBilinear_asymmetric_int8",
    "ResizeOpTest.ResizeOpLinearDownSampleTest_2DBilinear_pytorch_half_pixel",
    "ResizeOpTest.ResizeOpLinearDownSampleTest_3DTrilinear_pytorch_half_pixel",
    "ResizeOpTest.ResizeOpLinearUpSampleTest_5DTrilinear_pytorch_half_pixel",
    "ResizeOpTest.ResizeOpNearestUpSample_Nearest2xOptimization_Sizes",
  ],
  "RestorePaddingTest": [],
  "ReverseSequenceTest": [],
  "RMSNormalizationOpTest": [
    "RMSNormalizationOpTest.RMSNorm",
    "RMSNormalizationOpTest.RMSNorm_float16",
    "RMSNormalizationOpTest.RMSNorm_Scale",
    "RMSNormalizationOpTest.RMSNorm_Scale_Float16",
  ],
  "RNNTest": [
    "RNNTest.RNN_bidirectional_0",
    "RNNTest.RNN_bidirectional_1",
    "RNNTest.RNN_invalid_sequence_lens",
    "RNNTest.RNN_with_invalid_activation_load_failure",
  ],
  "RoiAlignTest": [],
  "RoIPoolTest": [],
  "RotaryEmbeddingTest": [],
  "RoundTest": [
    "RoundTest.SimpleTestDouble",
    "RoundTest.SimpleTestFloat",
    "RoundTest.SimpleTestFloat16",
  ],
  "Scan8": ["*"],
  "Scan9": ["*"],
  "Scatter": [
    "Scatter.IndicesUpdatesDontMatch",
    "Scatter.int8_t",
    "Scatter.InvalidIndex",
    "Scatter.MLFloat16",
  ],
  "ScatterElements": [
    "ScatterElements.AddReduction",
    "ScatterElements.AddReduction_MLFloat16",
    "ScatterElements.AddReductionAxis1",
    "ScatterElements.MaxReduction_Double",
    "ScatterElements.MaxReduction_Float",
    "ScatterElements.MaxReduction_MLFloat16",
    "ScatterElements.MinReduction_Double",
    "ScatterElements.MinReduction_Float",
    "ScatterElements.MinReduction_MLFloat16",
    "ScatterElements.MulReduction",
    "ScatterElements.MulReductionAxis1",
  ],
  "ScatterNDOpTest": [
    "ScatterNDOpTest.ScatterND_18_add",
    "ScatterNDOpTest.ScatterND_18_max",
    "ScatterNDOpTest.ScatterND_18_min",
    "ScatterNDOpTest.ScatterND_18_mul",
    "ScatterNDOpTest.ScatterND_18_mul_long_shape",
    "ScatterNDOpTest.ScatterND_3tensor_int64",
  ],
  "SequenceOpsTest": [],
  "ShapeInferenceTests": [],
  "ShapeOpTest": [
    "ShapeOpTest.ShapeOpset15_Default",
    "ShapeOpTest.ShapeOpset15_EndOnly",
    "ShapeOpTest.ShapeOpset15_StartAndEnd",
    "ShapeOpTest.ShapeOpset15_StartAndEndNegative",
    "ShapeOpTest.ShapeOpset15_StartAndEndProducingEmptySlice",
    "ShapeOpTest.ShapeOpset15_StartOnly",
    "ShapeOpTest.ShapeOpset19_Default",
    "ShapeOpTest.ShapeOpset21_Default",
    "ShapeOpTest.ShapeOpset23_Default",
  ],
  "SignalOpsTest": [],
  "SizeOpTest": [],
  "SkipGroupNormTest": [],
  "SkipLayerNormTest": [
    "SkipLayerNormTest.SkipLayerNormPrePack",
  ],
  "SliceTest/0": [],
  "SliceTest/1": [],
  "SliceTest": [
    "SliceTest.CoalesceDims",
    "SliceTest.OptionalAxesInputAloneMissing",
    "SliceTest.Slice1D_ReverseAllAxes_1",
    "SliceTest.Slice2D_ImplicitCopyBySlicingADimensionFully",
    "SliceTest.Slice2D_ReverseAllAxes",
    "SliceTest.Slice2D_ReverseSubsetOfAxes_1",
    "SliceTest.Slice2D_ReverseSubsetOfAxes_2",
    "SliceTest.Slice2D_ReverseSubsetOfNegAxes_1",
    "SliceTest.Slice5D_LargeStep",
    "SliceTest.Slice5D_SubsetOfAxes_Flatten2Dims_OffsetInput",
  ],
  "SoftmaxOperator": [
    "SoftmaxOperator.DimWithZero",
    "SoftmaxOperator.GH15949_regression_test",
    "SoftmaxOperator.InvalidAxis",
    "SoftmaxOperator.InvalidAxis_opset13",
    "SoftmaxOperator.Simple_fp16",
    "SoftmaxOperator.ThreeAndFourDimsAxis0",
    "SoftmaxOperator.ThreeAndFourDimsSecondLastAxis",
    "SoftmaxOperator.ThreeAndFourDimsSecondLastAxis_opset13",
  ],
  "SparseToDenseMatMul": [],
  "SplitOperatorTest": [
    "SplitOperatorTest.Axis0UnequalSplitFloat",
    "SplitOperatorTest.Axis0UnequalSplitInputFloat",
    "SplitOperatorTest.Axis0UnequalSplitInputFloat_not_initializer",
    "SplitOperatorTest.Axis0UnequalSplitString",
    "SplitOperatorTest.Axis1EqualSplitFloat",
    "SplitOperatorTest.Axis1EqualSplitFloat16",
    "SplitOperatorTest.Axis1EqualSplitString",
    "SplitOperatorTest.Axis1SplitMiddleDimensionEqually",
    "SplitOperatorTest.Axis1SplitMiddleDimensionUnequally",
    "SplitOperatorTest.Axis1UnequalSplitFloat",
    "SplitOperatorTest.Axis1UnequalSplitString",
    "SplitOperatorTest.Axis2EqualSplit",
    "SplitOperatorTest.Axis2UnequalSplit",
    "SplitOperatorTest.InvalidValueInSplitAttribute",
    "SplitOperatorTest.MissingOptionalInputAdded",
    "SplitOperatorTest.NegativeAxis",
    "SplitOperatorTest.Split18_InvalidNumOutputs",
    "SplitOperatorTest.Split18_NumOutputs_EvenSplit",
    "SplitOperatorTest.Split18_NumOutputs_UnevenSplit",
    "SplitOperatorTest.Split18_NumOutputsEvenSplitAxis1",
    "SplitOperatorTest.Split18_NumOutputsUnevenSplitAxis1",
    "SplitOperatorTest.Split3Inner",
    "SplitOperatorTest.SplitAttributeSumTooSmall",
    "SplitOperatorTest.Uint8Axis1SplitMiddleDimensionUnequally",
    "SplitOperatorTest.Uint8NegativeAxis",
    "SplitOperatorTest.ZeroSizeInput",
    "SplitOperatorTest.ZeroSizeOutput",
  ],
  "SqueezeOpTest": [
    "SqueezeOpTest.BadAxes",
    "SqueezeOpTest.BadAxes_opset13_bfloat16",
    "SqueezeOpTest.Squeeze_2_axes_input",
    "SqueezeOpTest.Squeeze_4d_2_axes_input",
    "SqueezeOpTest.Squeeze_4d_NegAxis_axes_input",
    "SqueezeOpTest.Squeeze_Empty_Axes_1",
    "SqueezeOpTest.Squeeze_Empty_Axes_1_bfloat16",
    "SqueezeOpTest.Squeeze_Empty_Axes_2",
    "SqueezeOpTest.Squeeze_Empty_Axes_2_bfloat16",
    "SqueezeOpTest.Squeeze_Empty_Axes_3",
    "SqueezeOpTest.Squeeze_Empty_Axes_3_bfloat16",
    "SqueezeOpTest.Squeeze_Empty_Axes_opset13",
    "SqueezeOpTest.SqueezeNegAxis_axes_input",
  ],
  "StringConcat": [],
  "StringSplit": [],
  "TensorOpTest/0": [],
  "TensorOpTest/1": [],
  "TensorOpTest/2": [],
  "TensorOpTest": [
    "TensorOpTest.Reshape",
    "TensorOpTest.Reshape_bfloat16",
    "TensorOpTest.Reshape_EmptyInputWithAllowZero",
    "TensorOpTest.Reshape_EmptyInputWithAllowZero_bfloat16",
    "TensorOpTest.Reshape_EmptyInputWithoutAllowZero",
    "TensorOpTest.Reshape_EmptyInputWithoutAllowZero_bfloat16",
    "TensorOpTest.Reshape_WithAllowZero",
    "TensorOpTest.Reshape_WithAllowZero_bfloat16",
    "TensorOpTest.Reshape_WithOutAllowZero",
    "TensorOpTest.Reshape_WithOutAllowZero_bfloat16",
    "TensorOpTest.ReshapeWithEmptyDim",
    "TensorOpTest.ReshapeWithEmptyDim_bfloat16",
    "TensorOpTest.ReshapeWithEmptyInput",
    "TensorOpTest.ReshapeWithEmptyInput_bfloat16",
    "TensorOpTest.ReshapeWithEmptyInputAndDynamicShape",
    "TensorOpTest.ReshapeWithEmptyInputAndDynamicShape_bfloat16",
    "TensorOpTest.ReshapeWithInitializer_bfloat16",
    "TensorOpTest.ShapeTest2D",
    "TensorOpTest.ShapeTest3D",
    "TensorOpTest.TileOverflowMultipleAxes",
    "TensorOpTest.TileOverflowRepeats1D",
    "TensorOpTest.TileOverflowRepeats2D",
    "TensorOpTest.TileOverflowRepeatsFirstAxis",
    "TensorOpTest.TileOverflowRepeatsInt32",
  ],
  "TfIdfVectorizerTest": [],
  "TopKOperator": [
    "TopKOperator.BigArrayBigTopKSorted",
    "TopKOperator.BigArrayBigTopKSorted_double",
  ],
  "TransposeOpTest/0": [],
  "TransposeOpTest/1": [],
  "TransposeOpTest": [
    "TransposeOpTest.NCHW2NHWCStr",
    "TransposeOpTest.NHWC2NCHW_String",
    "TransposeOpTest.SingleAxisMovingInwardsBlockCopy",
    "TransposeOpTest.SixDim",
    "TransposeOpTest.Transpose021",
    "TransposeOpTest.Transpose102",
    "TransposeOpTest.Transpose120",
    "TransposeOpTest.TransposeReshape",
    "TransposeOpTest.TwoDim_Int2_Mod4_0",
    "TransposeOpTest.TwoDim_Int2_Mod4_1",
    "TransposeOpTest.TwoDim_Int2_Mod4_2",
    "TransposeOpTest.TwoDim_Int2_Mod4_3",
    "TransposeOpTest.TwoDim_int8",
    "TransposeOpTest.TwoDim_mlfloat16",
    "TransposeOpTest.TwoDim_Odd_Int4",
    "TransposeOpTest.TwoDim_Odd_UInt4",
    "TransposeOpTest.TwoDim_UInt2_Mod4_0",
    "TransposeOpTest.TwoDim_UInt2_Mod4_1",
    "TransposeOpTest.TwoDim_UInt2_Mod4_2",
    "TransposeOpTest.TwoDim_UInt2_Mod4_3",
    "TransposeOpTest.TwoDimNoAttr",
  ],
  "TriluContribOpTest": [],
  "TriluOpTest": [],
  "TriluTest": [],
  "UnfoldTensorOpTest": [],
  "Unique": [],
  "UniqueOpTest": [
    "UniqueOpTest.Unique_AllUniqueElements",
    "UniqueOpTest.Unique_Complicated_Example",
    "UniqueOpTest.Unique_Example_SingleElement",
    "UniqueOpTest.Unique_Spec_Example",
  ],
  "UnpoolTest": [],
  "UnsqueezeOpTest": [
    "UnsqueezeOpTest.Unsqueeze_1",
    "UnsqueezeOpTest.Unsqueeze_1_bool",
    "UnsqueezeOpTest.Unsqueeze_1_int32",
    "UnsqueezeOpTest.Unsqueeze_1_int32_axes_input",
    "UnsqueezeOpTest.Unsqueeze_3_axes_input",
    "UnsqueezeOpTest.Unsqueeze_Duplicate",
    "UnsqueezeOpTest.Unsqueeze_OutOfRange",
    "UnsqueezeOpTest.UnsqueezeNegAxis_3",
  ],
  "UpsampleOpTest": [
    "UpsampleOpTest.NhwcUpsampleOp4D1CBilinearTest",
    "UpsampleOpTest.NhwcUpsampleOp4DBilinearTest_int32",
    "UpsampleOpTest.NhwcUpsampleOpNearest15XTest",
    "UpsampleOpTest.NhwcUpsampleOpNearest2XTest",
    "UpsampleOpTest.NhwcUpsampleOpNearest2XTest_int32",
    "UpsampleOpTest.NhwcUpsampleOpNearest2XTest_opset9",
    "UpsampleOpTest.NhwcUpsampleOpNearestTest",
    "UpsampleOpTest.NhwcUpsampleOpNearestTest_int32",
    "UpsampleOpTest.NhwcUpsampleOpNearestTest_uint8",
    "UpsampleOpTest.UpsampleOp2DBilinearTest",
    "UpsampleOpTest.UpsampleOp4DBilinearTest",
    "UpsampleOpTest.UpsampleOpNearest2XTest_int32",
    "UpsampleOpTest.UpsampleOpNearestTest_int32"
  ],
  "WhereOpTest": [],
  "WriteScores": [],
}

# Transform the exclusions to a string in gtest_filter's expected format
filter = []
for group_name, test_names in exclusions.items():
  if test_names == ["*"]:
    filter.append(f"{group_name}.*")
  elif test_names:
    filter.extend(test_names)

args = [
  sys.argv[1],
  "--gtest_output=xml:" + sys.argv[2],
  '--gtest_filter=-' + ":".join(filter),
]

print("args: ", args)

p = subprocess.Popen(
  args,
  text=True,
  universal_newlines=True,
  stdout=subprocess.PIPE,
  stderr=subprocess.STDOUT,
  shell=False
)

for line in p.stdout:
  print(line, end='')

p.stdout.close()
returncode = p.wait()

print(f"Process exited with exit code {returncode}.")
sys.exit(returncode)
