import os
import subprocess
import sys

print(f"cwd: {os.getcwd()}")
print(f"exe: {sys.argv[1]}")

args = [
  sys.argv[1],
  "--gtest_output=xml:" + sys.argv[2],
  '--gtest_filter=-"' + ":".join([
    "ActivationOpTest.Relu_fp16",
    "ActivationOpTest.Sigmoid_fp16",
    "ActivationOpTest.Tanh_fp16",
    "BatchNormTest.ForwardTrainingTest*",
    "BiasGeluTest.Float",
    "ConcatOpTest.Concat1D_*",
    "ConstantOfShape.DefaultValue",
    "ConstantOfShape.Float_Ones",
    "ConstantOfShape.Int32_Zeros",
    "ConvTransposeTest.*",
    "CropOpTest.Crop_*",
    "CumSumTest._1DTest",
    "CumSumTest.*",
    "DeformConvTest.*",
    "DequantizeLinearContribOpTest.DequantizeLinear_*",
    "DequantizeLinearOpMLFloat16Test.Float8",
    "DequantizeLinearOpMLFloat16Test.Scalar",
    "DequantizeLinearOpTest.*",
    "Dropout.WithOptionalOutputOpset10",
    "Dropout.WithOptionalOutputOpset7",
    "FlattenOpModelTest.Flatten_broadcast",
    "FlattenOpTest.Flatten_*",
    "FusedMatMulOpTest.Float16_NoTranspose",
    "GatherElementsOpTest.IndicesOutOfBounds",
    "GatherOpTest.Gather_axis1_*",
    "GemmOpTest.Gemm2DBroadcast_*",
    "GemmOpTest.GemmNaN_bfloat16",
    "GemmOpTest.GemmNoTrans_f16",
    "GemmOpTest.GemmScalarBroadcast_bfloat16",
    "GemmOpTest.GemmTransB_f16",
    "GemmOpTypedTests.*",
    "Identity.OptionalTensorSequenceType_None",
    "Identity.OptionalTensorSequenceType_NonNone",
    "Identity.OptionalTensorType_None",
    "Identity.OptionalTensorType_NonNone",
    "Identity.StringType",
    "If.TestIfWithOptionalTypeTensorAsOutput",
    "ImageScalerContribOpTest.ImageScalerTest",
    "InstanceNormalizationOpTest.*",
    "LayerNormTest.*",
    "MathOpTest.Abs_int32",
    "MathOpTest.Abs_int8",
    "MathOpTest.Add_*",
    "MathOpTest.Clip*",
    "MathOpTest.CosDouble",
    "MathOpTest.DimWithZeroHandling",
    "MathOpTest.Div_int32",
    "MathOpTest.Div_int64",
    "MathOpTest.Equal_*",
    "MathOpTest.Exp_double",
    "MathOpTest.Exp_float",
    "MathOpTest.Greater_9_*",
    "MathOpTest.GreaterOrEqual_*",
    "MathOpTest.Less_*",
    "MathOpTest.LessOrEqual*",
    "MathOpTest.MatMul_Float16",
    "MathOpTest.Max_*",
    "MathOpTest.Mean_6",
    "MathOpTest.Mean_8",
    "MathOpTest.Min_*",
    "MathOpTest.Mul_int32",
    "MathOpTest.Neg_*",
    "MathOpTest.Shrink*",
    "MathOpTest.Sub_int32",
    "MathOpTest.Sum_*",
    "ModOpTest.Int8_mixed_sign",
    "ModOpTest.Int8_mixed_sign_fmod",
    "NhwcFp16PoolOpTest.AvgPoolIncludePadPixel",
    "NonMaxSuppressionOpTest.InvalidIOUThreshold",
    "OptionalOpTest.Optional*",
    "PadOpTest.BoolType",
    "PadOpTest.*",
    "PoolFp16Test.*",
    "PoolTest.*",
    "QuantizeLinearContribOpTest.*",
    "QuantizeLinearMatmulOpTest.QLinearMatMulPrePack",
    "QuantizeLinearOpMLFloat16Test.Uint8",
    "QuantizeLinearOpTest.*",
    "Random.RandomUniform1DFloat",
    "ReductionOpTest.ArgMax*",
    "ReductionOpTest.ArgMin*",
    "ReductionOpTest.Reduce*",
    "ResizeOpTest.Antialias_Large_half_pixel",
    "ResizeOpTest.Axes_and_Scale_18",
    "ResizeOpTest.*",
    "RMSNormalizationOpTest.RMSNorm*",
    "RNNTest.RNN_*",
    "RoundTest.*",
    "Scan8.OuterScopeAccess_NoShapeInMainGraph_TypeAndShapeInSubgraph",
    "Scan8.OuterScopeAccess_NoShapeInMainGraph_NoTypeAndShapeInSubgraph",
    "Scatter.IndicesUpdatesDontMatch",
    "Scatter.MLFloat16",
    "ScatterElements.*",
    "ScatterNDOpTest.*",
    "ShapeOpTest.*",
    "SkipLayerNormTest.SkipLayerNormPrePack",
    "SliceTest.OptionalAxesInputAloneMissing",
    "SoftmaxOperator.*",
    "SplitOperatorTest.*",
    "SqueezeOpTest.*",
    "TensorOpTest.*",
    "TensorOpTest.*",
    "TransposeOpTest.*",
    "UniqueOpTest.*",
    "UnsqueezeOpTest.*",
    "UpsampleOpTest.*",
  ]) + '"'
]

print("args: ", args)

p = subprocess.Popen(
  args,
  text=True,
  universal_newlines=True,
  stdout=subprocess.PIPE,
  stderr=subprocess.STDOUT,
  shell=False
)

for line in p.stdout:
  print(line, end='')

p.stdout.close()
returncode = p.wait()

print(f"Process exited with exit code {returncode}.")
sys.exit(returncode)
