name: "Linux x64 CUDA"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

# Build Image #########################################################################################################

  build-image:
    if: false
    strategy:
      fail-fast: false
      matrix:
        cuda_version: ['12.9'] # , '13.0']
        trt_version: ['10.14.1.48']

    runs-on: [
      "self-hosted",
      "1ES.Pool=onnxruntime-ep-Ubuntu2404-AMD-CPU",
      "JobId=trtep-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
    ]
    name: Build Image CUDA${{ matrix.cuda_version }} TRT${{ matrix.trt_version }}
    environment: Linux_x64
    env:
      AZCOPY_AUTO_LOGIN_TYPE: ${{ vars.AZCOPY_AUTO_LOGIN_TYPE }}
      AZCOPY_MSI_CLIENT_ID: ${{ vars.AZCOPY_MSI_CLIENT_ID }}
      CMAKE_CUDA_ARCHITECTURES: 86
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
      with:
        sparse-checkout: .github
        sparse-checkout-cone-mode: false

    - name: Build Docker Image
      uses: microsoft/onnxruntime-github-actions/build-docker-image@v0.0.12
      id: build_docker_image_step
      with:
        dockerfile: ${{ github.workspace }}/.github/docker/Dockerfile.ubuntu_2404_cuda
        image-name: ghcr.io/onnxruntime/onnxruntime-ep-tensorrt/ubuntu_2404_cuda${{ matrix.cuda_version }}_trt${{ matrix.trt_version}}
        build-args: 'BASE_IMAGE=nvidia/cuda:${{ matrix.cuda_version }}.1-cudnn-devel-ubuntu24.04 TRT_VERSION=${{ matrix.trt_version}}-1+cuda${{ matrix.cuda_version }} CMAKE_CUDA_ARCHITECTURES=${{ env.CMAKE_CUDA_ARCHITECTURES }} --network=host'
        pull: false
        push: true
        azure-container-registry-name: onnxruntimebuildcache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Write output
      run: |
        echo 'cuda_version=${{ matrix.cuda_version }}' >> job_${{ strategy.job-index }}
        echo 'trt_version=${{ matrix.trt_version }}' >> job_${{ strategy.job-index }}
        echo 'full-image-name=${{ steps.build_docker_image_step.outputs.full-image-name }}' >> job_${{ strategy.job-index }}

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: job_${{ strategy.job-index }}
        path: job_${{ strategy.job-index }}

# Build Matrix ########################################################################################################

  build-matrix:
    if: false
    runs-on: ubuntu-latest
    needs: build-image
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    name: Build Strategy Matrix
    permissions:
      contents: read

    # NOTE: GHA doesn't yet support passing outputs from multiple jobs run thru' strategy matrix. To work around that
    # limitation, each job in the strategy matrix uploads an artifact with the information it intends to pass downstream.
    # A separate job collects all the artifacts and builds the matrix. For more information see below -
    #   - https://github.com/actions/runner/pull/2477
    #   - https://github.com/orgs/community/discussions/25634
    #   - https://github.com/orgs/community/discussions/17245

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        pattern: 'job_*'
        merge-multiple: true

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
  
    - name: Generate matrix
      id: gen-matrix
      shell: python
      run: |
        import json
        import os
        from pathlib import Path

        matrix = []
        for fp in Path('.').glob('job_*'):
          with fp.open() as strm:
            job_def = {}
            for line in strm:
              parts = line.strip().split('=')
              job_def[parts[0]] = parts[1]
            matrix.append({'build_type': 'Debug', **job_def})
            matrix.append({'build_type': 'RelWithDebInfo', **job_def})

        print(json.dumps(matrix))
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f'matrix={json.dumps(matrix)}', file=fh)

# Build TRT EP ########################################################################################################

  build-trtep:
    if: false
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    runs-on: [
      "self-hosted",
      "1ES.Pool=onnxruntime-ep-Ubuntu2404-AMD-CPU",
      "JobId=trtep-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
    ]
    needs: build-matrix
    name: Build TRTEp Linux-x64 CUDA${{ matrix.config.cuda_version }} TRT${{ matrix.config.trt_version }} ${{ matrix.config.build_type }}
    container: ${{ matrix.config.full-image-name }}
    environment: Linux_x64
    env:
      AZCOPY_AUTO_LOGIN_TYPE: ${{ vars.AZCOPY_AUTO_LOGIN_TYPE }}
      AZCOPY_MSI_CLIENT_ID: ${{ vars.AZCOPY_MSI_CLIENT_ID }}
      ARTIFACT_NAME: Linux_x64_cuda${{ matrix.config.cuda_version }}_trt${{ matrix.config.trt_version }}_${{ matrix.config.build_type }}
    permissions:
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-cuda${{ matrix.config.cuda_version }}-trt${{ matrix.config.trt_version }}-${{ matrix.config.build_type }}

    - name: Run the build
      run: |
        env
        which cmake && cmake --version
        which ninja && ninja --version
        which $CC && $CC --version
        which $CXX && $CXX --version
        which ccache && ccache --version
        where python && python --version

        cmake                                                       \
            -G Ninja                                                \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}      \
            -DCMAKE_INSTALL_PREFIX=out/${{ env.ARTIFACT_NAME }}     \
            -DCMAKE_CUDA_ARCHITECTURES=${CMAKE_CUDA_ARCHITECTURES}  \
            -DCMAKE_CUDA_COMPILER=${CUDA_HOME}/bin/nvcc             \
            -DTENSORRT_HOME=${TRT_HOME}                             \
            -S . -B out/build
        cmake --build out/build -j `nproc`
        cmake --install out/build

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: out/${{ env.ARTIFACT_NAME }}

# Build ORT ###########################################################################################################

  build-ort:
    if: false
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    runs-on: [
      "self-hosted",
      "1ES.Pool=onnxruntime-ep-Ubuntu2404-AMD-CPU",
      "JobId=trtep-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
    ]
    needs: build-matrix
    name: Build ORT Linux-x64 CUDA${{ matrix.config.cuda_version }} ${{ matrix.config.build_type }}
    container: ${{ matrix.config.full-image-name }}
    environment: Linux_x64
    env:
      ALLOW_RELEASED_ONNX_OPSET_ONLY: '0'
      ARTIFACT_NAME: ort_linux_x64_cuda${{ matrix.config.cuda_version }}_${{ matrix.config.build_type }}
      AZCOPY_AUTO_LOGIN_TYPE: ${{ vars.AZCOPY_AUTO_LOGIN_TYPE }}
      AZCOPY_MSI_CLIENT_ID: ${{ vars.AZCOPY_MSI_CLIENT_ID }}
      CMAKE_CUDA_ARCHITECTURES: 86
      ONNXRUNTIME_TEST_GPU_DEVICE_ID: '0'
    permissions:
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
      with:
        repository: microsoft/onnxruntime
        ref: 'rel-1.25.0'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        architecture: x64

    - name: Install python modules
      run: python -m pip install -r ./tools/ci_build/github/linux/python/requirements.txt

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-cuda${{ matrix.config.cuda_version }}-trt${{ matrix.config.trt_version }}-${{ matrix.config.build_type }}

    - name: Build and Clean Binaries
      run: |
        env
        # Caution with the use of github.workspace here. In containers,
        #   ${{ github.workspace }} != $GITHUB_WORKSPACE
        # Same is true for ${{ runner.temp }} and $RUNNER_TEMP
        # Reported issue -
        # https://github.com/actions/runner/issues/2058
        
        # Execute the build process
        python $GITHUB_WORKSPACE/tools/ci_build/build.py \
          --build \
          --update \
          --config ${{ matrix.config.build_type }} \
          --build_dir build \
          --use_cache \
          --skip_submodule_sync \
          --parallel \
          --cmake_generator "Ninja" \
          --build_shared_lib \
          --target onnxruntime_provider_test

        # Clean up the output directory before uploading artifacts
        export outputDir="build/${{ matrix.config.build_type }}"

        rm -rf "$outputDir/_deps"
        rm -rf "$outputDir/CMakeCache.txt"
        rm -rf "$outputDir/CMakeFiles"
        rm -rf "$outputDir/lib"
        rm -rf "$outputDir/models"
        rm -rf "$outputDir/onnxruntime"
        rm -rf "$outputDir/pybind11"
        rm -rf "$outputDir/vcpkg_installed"
        find $outputDir -type f -name '*.a' -delete
        find $outputDir -type f -name '*.obj' -delete
        find $outputDir -type f -name '*.pch' -delete
        find $outputDir -type f -name '*.tlog' -delete

        # Move the testdata folder under the output folder so
        # it gets included as part of the artifact
        mv onnxruntime/test/testdata $outputDir/.

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: build/${{ matrix.config.build_type }}

# Run Tests ###########################################################################################################

  run-tests:
    if: false
    strategy:
      fail-fast: false
      matrix:
        build_type: [RelWithDebInfo]  # Debug
        cuda_version: ['12.9'] #, '13.0'
        trt_version: ['10.14.1.48']

    runs-on: [
      "self-hosted",
      "1ES.Pool=onnxruntime-ep-github-linux-a10",
      "1ES.ImageOverride=onnxruntime-ubuntu2204-CUDA-A10",
      "JobId=trtep-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
    ]
    name: Test CUDA${{ matrix.cuda_version }} TRT${{ matrix.trt_version }} ${{ matrix.build_type }}
    needs: [build-trtep, build-ort]
    container:
      image: 'ghcr.io/onnxruntime/onnxruntime-ep-tensorrt/ubuntu_2404_cuda12.9_trt10.14.1.48:sha256-463d90a20a513420863d8ba847891eaa5b23eb544dff9863667a503eee6ad850'
      options: --gpus all
    environment: Linux_x64
    env:
      ALLOW_RELEASED_ONNX_OPSET_ONLY: '0'
      AZCOPY_AUTO_LOGIN_TYPE: ${{ vars.AZCOPY_AUTO_LOGIN_TYPE }}
      AZCOPY_MSI_CLIENT_ID: ${{ vars.AZCOPY_MSI_CLIENT_ID }}
      CMAKE_CUDA_ARCHITECTURES: 86
      ONNXRUNTIME_TEST_GPU_DEVICE_ID: '0'
      ARTIFACT_NAME: orttrtep_cuda${{ matrix.cuda_version }}_trt${{ matrix.trt_version }}_${{ matrix.build_type }}.results
      BUILD_TYPE: ${{ matrix.build_type }}
      CUDA_VERSION: ${{ matrix.cuda_version }}
      TRT_VERSION: ${{ matrix.trt_version }}
    permissions:
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
      with:
        sparse-checkout: .github
        sparse-checkout-cone-mode: false

    - name: Download TRTEp artifacts
      uses: actions/download-artifact@v7
      with:
        name: Linux_x64_cuda${{ matrix.cuda_version }}_trt${{ matrix.trt_version }}_${{ matrix.build_type }}
        path: orttrtep

    - name: Download ORT artifacts
      uses: actions/download-artifact@v7
      with:
        name: 'ort_linux_x64_cuda${{ matrix.cuda_version }}_${{ matrix.build_type }}'
        path: onnxruntime

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        architecture: x64

    - name: Setup library path
      run: |
        echo "TRTEP_LIBRARY_PATH=$GITHUB_WORKSPACE/orttrtep/lib/libORTTensorRTEp.so" >> $GITHUB_ENV

    - name: Run tests
      env:
        ORT_UNIT_TEST_MAIN_LOG_LEVEL: 0
        ORT_TRT_EP_ENABLE_BUILDER_PLACEHOLDER: 1
        ORT_UNIT_TEST_MAIN_DYNAMIC_PLUGIN_EP_CONFIG_JSON: |
          {
            "ep_library_registration_name": "NvTensorRtRtx",
            "ep_library_path": ${{ toJson(env.TRTEP_LIBRARY_PATH) }},
            "selected_ep_name": "NvTensorRtRtx",
            "default_ep_options": {}
          }
      run: |
        env
        chmod +x "$GITHUB_WORKSPACE/onnxruntime/onnxruntime_provider_test"
        python "$GITHUB_WORKSPACE/.github/scripts/test_runner.py"   \
          "$GITHUB_WORKSPACE/onnxruntime/onnxruntime_provider_test" \
          "${{ env.ARTIFACT_NAME }}"

    - name: Upload build artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
            ${{ env.ARTIFACT_NAME }}.xml
            ${{ env.ARTIFACT_NAME }}.log

# Packaging ###########################################################################################################

  packaging:
    strategy:
      fail-fast: false
      matrix:
        build_type: [RelWithDebInfo] # Debug
        cuda_version: ['12.9'] #, '13.0']
        trt_version: ['10.14.1.48']

    runs-on: [
      "self-hosted",
      "1ES.Pool=onnxruntime-ep-github-linux-a10",
      "1ES.ImageOverride=onnxruntime-ubuntu2204-CUDA-A10",
      "JobId=trtep-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
    ]
    name: Pack CUDA${{ matrix.cuda_version }} TRT${{ matrix.trt_version }} ${{ matrix.build_type }}
    # needs: [run-tests]
    container:
      image: 'ghcr.io/onnxruntime/onnxruntime-ep-tensorrt/ubuntu_2404_cuda12.9_trt10.14.1.48:sha256-463d90a20a513420863d8ba847891eaa5b23eb544dff9863667a503eee6ad850'
      options: --gpus all
    environment: Linux_x64
    env:
      AZCOPY_AUTO_LOGIN_TYPE: ${{ vars.AZCOPY_AUTO_LOGIN_TYPE }}
      AZCOPY_MSI_CLIENT_ID: ${{ vars.AZCOPY_MSI_CLIENT_ID }}
      ARTIFACT_NAME: orttrtep_cuda${{ matrix.cuda_version }}_trt${{ matrix.trt_version }}_${{ matrix.build_type }}
      BUILD_TYPE: ${{ matrix.build_type }}
      CUDA_VERSION: ${{ matrix.cuda_version }}
      TRT_VERSION: ${{ matrix.trt_version }}
    permissions:
      contents: read

    steps:
    # - name: Setup .NET SDK
    #   uses: actions/setup-dotnet@v5
    #   env:
    #     PROCESSOR_ARCHITECTURE: x64
    #   with:
    #     dotnet-version: '9.x'

    # - name: Use Nuget
    #   uses: nuget/setup-nuget@v4
    #   with:
    #     nuget-version: '6.x'

    - name: Checkout Code
      uses: actions/checkout@v6
      with:
        sparse-checkout: csharp/Microsoft.ML.OnnxRuntime.EP.TensorRT
        sparse-checkout-cone-mode: false

    - name: Download TRTEp artifacts
      uses: actions/download-artifact@v7
      with:
        name: Linux_x64_cuda${{ matrix.cuda_version }}_trt${{ matrix.trt_version }}_${{ matrix.build_type }}
        run-id: '24531338476'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path: orttrtep

    - name: Build Nuget Package
      shell: pwsh
      run: |
        $SourceDir = ".\orttrtep\bin"
        $TargetDir = ".\csharp\Microsoft.ML.OnnxRuntime.EP.TensorRT\runtimes\win-x64\native"
        $null = New-Item -Type Directory -Force $TargetDir
        Move-Item "$SourceDir\ORTTensorRTEp.dll" -Destination $TargetDir
        Move-Item "$SourceDir\ORTTensorRTEp.pdb" -Destination $TargetDir

        Get-ChildItem -Path "$TargetDir"
        cd csharp\Microsoft.ML.OnnxRuntime.EP.TensorRT

        dotnet pack Microsoft.ML.OnnxRuntime.EP.TensorRT.csproj -c ${env:BUILD_TYPE}

    - name: Upload build artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          ./csharp/Microsoft.ML.OnnxRuntime.EP.TensorRT/bin/${{ matrix.build_type }}/Microsoft.ML.OnnxRuntime.EP.TensorRT.*.nupkg
          ./csharp/Microsoft.ML.OnnxRuntime.EP.TensorRT/bin/${{ matrix.build_type }}/Microsoft.ML.OnnxRuntime.EP.TensorRT.*.snupkg