name: "Main"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  workflow_dispatch:


env:
  PYTHON_VERSION: "3.x"
  CMAKE_CUDA_ARCHITECTURES: 80


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: echo "Hello World!"
